---
title: "improving initital estimate"
author: "Andrew Glover"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
---

```{r purling, eval=FALSE, include=FALSE, purl=FALSE}
#### run this to purl the r code to the /R file, this seems to not be able to run with the knit
knitr::purl(input = "calc_power_funcs.Rmd",
            output = stringr::str_c(rprojroot::find_rstudio_root_file(),"/R/calc_power_funcs.R") #puts file in /R)
            ) 

``` 


```{r setup, include=FALSE, purl=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::load_all() #can't purl this function, it will cause in infinite loop when another document purls
```

We will make a couple of assumptions: 

1. Athletic performance is completely determined by Banister's FF model
2. $p_0$ is exact and we don't have to estimate it 
3. There is no noise in estimating the parameters or performance

The goal of this document is to try to get a good initial estimate for the 
parameters for our new algorithm and for RLS. 

# Generating Data

```{r}

```

