---
title: "junk code"
author: "Andrew Glover"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



<!-- ```{r} -->
<!-- min_params <- function(params_matrix, -->
<!--                        training_load, -->
<!--                        obs_perf, -->
<!--                        old_params, -->
<!--                        lambda) { -->
<!--   min_params <- old_params -->
<!--   obs_indexes <- which(!is.na(obs_perf)) -->
<!--   n <- length(obs_indexes) -->
<!--   min_cost <- sqrt(SSE(old_params, training_load, obs_perf)/n) -->
<!--   for (i in 1:nrow(params_matrix)){ -->
<!--     params_i <- as.numeric(params_matrix[i, ]) -->
<!--     params_dist_i <- params_dist(params_i, old_params) -->
<!--     SSE_i <- 0; cost_i <- 0 -->
<!--     p_0 <- params_i[[1]] -->
<!--     k_1 <- params_i[[2]]; k_2 <- params_i[[3]] -->
<!--     coef_1 <- exp(-1/params_i[[4]]); coef_2 <- exp(-1/params_i[[5]]) -->
<!--     T_1 <- 0; T_2 <- 0 -->
<!--     lower_index <- 1 -->
<!--     j <- 0 -->
<!--     for (new_index in obs_indexes) { -->
<!--       for (t in lower_index:new_index) { -->
<!--         T_1 <- coef_1*(T_1 + k_1*training_load[[t]]) -->
<!--         T_2 <- coef_2*(T_2 + k_2*training_load[[t]]) -->
<!--       } -->
<!--       SSE_i <- SSE_i + (p_0 + T_1 - T_2 - obs_perf[[new_index]])^2 -->
<!--       j <- j + 1 -->
<!--       lower_index <- new_index + 1 -->
<!--       if(min_cost < sqrt(SSE_i/n) + lambda*params_dist_i) { -->
<!--         break # goes to next set of parameters -->
<!--         # for a lot of the sets of parameters,  -->
<!--         # the condition should trigger on the first few data points -->
<!--       } -->
<!--       if (j == n && min_cost > sqrt(SSE_i/n) + lambda*params_dist_i) { -->
<!--         # the second condition helps with stability, if two different sets -->
<!--         # of parameters have the same cost -- namely when they both have 0 cost -- -->
<!--         # we will pick our previous point -->
<!--         min_cost <- sqrt(SSE_i/n) + lambda*params_dist_i -->
<!--         min_params <- params_i -->

<!--       } -->
<!--       else { -->
<!--         # do nothing; go to the next loop -->
<!--       } -->
<!--     } -->
<!--   } -->
<!--   return(list("cost" = min_cost, "opt_params" = min_params)) -->
<!-- } -->

<!-- # this function creates (or calls, we will see) the parameter matrix and applies  -->
<!-- # it to the previous function. makes things tider in the algorithm funciton -->
<!-- update_params_opt <- function(old_params,  -->
<!--                           training_load, -->
<!--                           sub_obs_perf, -->
<!--                           bounds_type = list("test"), -->
<!--                           lambda -->
<!--                           ) { -->
<!--   if(bounds_type == "test") { -->
<!--     params_matrix <- expand.grid(p_0 = 500, -->
<!--                                   k_1 = c(1,2,3,4), -->
<!--                                   k_2 = c(2,4,6,8), -->
<!--                                   tau_1 = c(5:35), -->
<!--                                   tau_2 = c(5:35)) -->
<!--   } -->
<!--   params_matrix <- params_matrix[params_matrix$tau_1 <= params_matrix$tau_2,] -->

<!--   getting_params_ouput <- min_params(params_matrix, -->
<!--                                   training_load, -->
<!--                                   sub_obs_perf, -->
<!--                                   old_params, -->
<!--                                   lambda = lambda) -->

<!--   out_list <- list() -->
<!--   out_list$opt_params <- getting_params_ouput$opt_params -->
<!--   out_list$cost <- getting_params_ouput$cost -->
<!--   return(out_list) -->
<!-- } -->

<!-- ``` -->


<!-- ```{r, warning = FALSE, eval = FALSE, include = FALSE} -->
<!-- days_test <- 200 -->
<!-- test_tr <- c(rep(100, days_test)) -->
<!-- test_params <- c(500, 1, 2, 25, 10) -->
<!-- true_model <- invariant_perf(c(500, 1, 2, 25, 10), training_load = test_tr) -->

<!-- obs_perf_test <- c(rep(NA, 19), 100, rep(NA, 19), 475,  -->
<!--               rep(NA,19), 730, rep(NA, 19), 860,  -->
<!--               rep(NA, 19), 900, rep(NA, days_test - 100)) -->

<!-- test_pred_perf <- new_pred_perf( -->
<!--   init_params = test_params, -->
<!--   training_load = test_tr , -->
<!--   obs_perf = obs_perf_test, -->
<!--   lambda = 3 -->
<!--   # found this value by trial and error -->
<!-- ) -->

<!-- test_pred_perf$perf_plot -->
<!-- test_pred_perf$params_plots -->

<!-- #################################### -->
<!-- # add p_0 to invariand_perf, b/c (star) -->
<!-- #################################### -->


<!-- ``` -->



<!-- ```{r first try at update params, eval = FALSE, include = FALSE} -->
<!-- cost_perf <- function(params, -->
<!--                       old_params, -->
<!--                       training_load, -->
<!--                       obs_perf, -->
<!--                       lambda = 1 -->
<!--                       ) { -->
<!--   sqrt(SSE(params, training_load, obs_perf)/length(obs_perf)) + # the SSE fits the suggested parameters -->
<!--     # against the old data, might add a forgetting factor to localize the fitting -->
<!--     ## added the square root because it seems that, if it is not there,  -->
<!--     ## the SSE term will dominate the params_dist term for large( like 5) terms no  -->
<!--     ## matter what the lamda term is -->
<!--     lambda*params_dist(params, old_params)  -->
<!--   ##################################################### -->
<!--   # might add some forgeting factor here can do later -->
<!--   ##################################################### -->
<!-- } -->

<!-- # params matrix in order k_1, k_2, tau_1, tau_2 -->

<!-- update_params <- function(old_params,  -->
<!--                           training_load, -->
<!--                           sub_obs_perf, -->
<!--                           bounds_type = list("test"), -->
<!--                           lambda = 1  -->
<!--                           ) { -->

<!--   if(bounds_type == "test") { -->
<!--     params_matrix <<- expand.grid(p_0 = 500, -->
<!--                                   k_1 = c(1,2,3,4), -->
<!--                                   k_2 = c(2,4,6,8), -->
<!--                                   tau_1 = c(5:35), -->
<!--                                   tau_2 = c(5:35)) -->
<!--   } -->
<!--   params_matrix <- params_matrix[params_matrix$tau_1 <= params_matrix$tau_2,] -->

<!--   cost_vec <- apply(params_matrix, -->
<!--                   1,  -->
<!--                   cost_perf, -->
<!--                   old_params = old_params, -->
<!--                   training_load = training_load, -->
<!--                   obs_perf = sub_obs_perf, -->
<!--                   lambda = lambda -->
<!--                   ) -->

<!--   out_list <- list() -->
<!--   out_list$opt_params <- params_matrix[which(cost_vec==min(cost_vec)), ] -->
<!--   out_list$cost <- cost_vec[[which(cost_vec==min(cost_vec))]] -->
<!--   out_list$mult_mins <- FALSE -->
<!--   if (length(which(cost_vec==min(cost_vec)))>1) { -->
<!--     out_list$mult_mins <- list(TRUE, which(cost_vec==min(cost_vec))) -->
<!--   } -->
<!--   return(out_list) -->
<!-- } -->

<!-- ### Code from inside new_pred -->
<!-- #  -->
<!-- #        -->
<!-- #       # so the old code is compatible with this,  -->
<!-- #       if (optimize == FALSE) { -->
<!-- #         params_output <- update_params( -->
<!-- #           old_params = curr_params, -->
<!-- #           training_load = training_load, -->
<!-- #           sub_obs_perf = obs_perf[1:i], -->
<!-- #           # the subset up to observation -->
<!-- #           bounds_type = bounds_type, -->
<!-- #           lambda = lambda -->
<!-- #         ) -->
<!-- #         curr_params <- params_output$opt_params -->
<!-- #         curr_cost <- params_output$cost -->
<!-- #       } -->
<!-- ``` -->

```{r algorithm function, purl = TRUE}
new_pred_perf <- function(init_params,
                          training_load,
                          obs_perf,
                          bounds_type = list("test"),
                          lambda) {
  # initializations
  curr_params <- init_params 
  curr_cost <- 0
  ####
  # curr_params take form c(p_0, k_1, k_2, tau_1, tau_2), to work with the time-invariant
  # functions
  ###
  
  matrix_params <- matrix(0, nrow = length(training_load), ncol = 5)
  colnames(matrix_params) <- c("p_0", "k_1", "k_2", "tau_1", "tau_2")

  days <- length(training_load)
  perf_out <- c(rep(curr_params[[1]], days + 1))
  cost_vec <- c(rep(0, days + 1))
  T_1 <- 0
  T_2 <- 0
  
  # doing the algorithm
  for (i in 1:length(obs_perf )) {
    # update params if there is new information
    if (is.na(obs_perf[[i]]) == FALSE) {
      params_output <- update_params_opt(
        old_params = init_params,
        training_load = training_load,
        sub_obs_perf = obs_perf[1:i],
        # the subset up to observation
        bounds_type = bounds_type,
        lambda = lambda
      )
      curr_params <- params_output$opt_params
      curr_cost <- params_output$cost

    } else {
    } # pass
    T_1 <- exp(-1 / curr_params[[4]]) * (T_1 + curr_params[[2]] * training_load[[i]])
    # training load index is i-1 since i starts at 2
    T_2 <- exp(-1 / curr_params[[5]]) * (T_2 + curr_params[[3]] * training_load[[i]])
    perf_out[[i+1]] <- curr_params[[1]] +  T_1 - T_2
    cost_vec[[i]] <- curr_cost 
    ##############
    # fix cost it is wrong, 
    #############
    matrix_params[i, ] <- as.numeric(curr_params)
  }
  
  #plotting
  params_data <- tibble(
    "day" = 0:length(training_load),
    "k_1" = as.numeric(c(matrix_params[1, "k_1"], matrix_params[, "k_1"])),
    "k_2" = as.numeric(c(matrix_params[1, "k_2"], matrix_params[, "k_2"])),
    "tau_1" = as.numeric(c(matrix_params[1, "tau_1"], matrix_params[, "tau_1"])),
    "tau_2" = as.numeric(c(matrix_params[1, "tau_2"], matrix_params[, "tau_2"])),
    "p_0" = as.numeric(c(matrix_params[1, "p_0"], matrix_params[, "p_0"]))
  )
  k_plot <- ggplot(params_data, aes(x = day)) +
    geom_line(aes(y = k_1, color = "k_1")) +
    geom_line(aes(y = k_2, color = "k_2"))

  tau_plot <- ggplot(params_data, aes(x = day)) +
    geom_line(aes(y = tau_1, color = "tau_1")) +
    geom_line(aes(y = tau_2, color = "tau_2"))

  #outputs
  out_list <- list()
  out_list$performance <- perf_out
  out_list$cost_vec <- cost_vec
  out_list$perf_plot <- plot_perf(obs_perf, perf_out)
  out_list$params_plots <- k_plot + tau_plot
  return(out_list)
} 
```

